language: python
python:
- 2.7
- 3.3
- 3.4
sudo: false
addons:
  apt:
    packages:
    - libcairo2-dev
before_install:
- if [ "v${TRAVIS_PYTHON_VERSION%%.*}" == "v2" ];
    then wget http://www.cairographics.org/releases/py2cairo-1.10.0.tar.bz2;
  fi
- if [ "v${TRAVIS_PYTHON_VERSION%%.*}" == "v3" ];
    then wget http://www.cairographics.org/releases/pycairo-1.10.0.tar.bz2;
  fi
install:
- tar xf py*cairo-1.10.0.tar.bz2
- cd py*cairo-1.10.0
- if [ "v$TRAVIS_PYTHON_VERSION" == "v3.4" ];
    then export PYTHON_CONFIG=/opt/python/3.4.2/lib/python3.4/config-3.4m/python-config.py;
  fi
- ./waf configure --prefix=$(python -c "import sys; print(sys.prefix)")
- ./waf build
- ./waf install
- cd ..
- pip install sphinx coveralls
script:
- coverage run "--include=MiniParse/*" setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  user: jacquev6
  password:
    secure: ZhNIHNDInYn+f2Hl05T4iy7deNwCC72dm/cvvaKfNp/lVJuC5B5BivmOgIfsjSDCCBPSI1OFGD3VwY7ihGH6TwyAGjIhdrkLux9Zy3+tlX4EPlXTzJaOh1wVWnKIFfUimI+ulumkYlrka7G1PcR4CmREKmRcj59OrAl/mRqoHmU=
  on:
    tags: true
    repo: jacquev6/MiniParse
    python: 2.7
